2023-05-23T13:39:29.248718+00:00 app[web.1]: import_module(entry)
2023-05-23T13:39:29.248718+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
2023-05-23T13:39:29.248718+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2023-05-23T13:39:29.248719+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:39:29.248719+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2023-05-23T13:39:29.248719+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2023-05-23T13:39:29.248719+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
2023-05-23T13:39:29.248719+00:00 app[web.1]: ModuleNotFoundError: No module named 'taggit'
2023-05-23T13:39:29.248720+00:00 app[web.1]: [2023-05-23 13:39:29 +0000] [7] [ERROR] Exception in worker process
2023-05-23T13:39:29.248720+00:00 app[web.1]: Traceback (most recent call last):
2023-05-23T13:39:29.248720+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-05-23T13:39:29.248720+00:00 app[web.1]: worker.init_process()
2023-05-23T13:39:29.248720+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-05-23T13:39:29.248720+00:00 app[web.1]: self.load_wsgi()
2023-05-23T13:39:29.248720+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-05-23T13:39:29.248720+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2023-05-23T13:39:29.248721+00:00 app[web.1]: ^^^^^^^^^^^^^^^
2023-05-23T13:39:29.248721+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-05-23T13:39:29.248721+00:00 app[web.1]: self.callable = self.load()
2023-05-23T13:39:29.248721+00:00 app[web.1]: ^^^^^^^^^^^
2023-05-23T13:39:29.248721+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-05-23T13:39:29.248721+00:00 app[web.1]: return self.load_wsgiapp()
2023-05-23T13:39:29.248721+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^
2023-05-23T13:39:29.248722+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-05-23T13:39:29.248725+00:00 app[web.1]: return util.import_app(self.app_uri)
2023-05-23T13:39:29.248725+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:39:29.248725+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
2023-05-23T13:39:29.248725+00:00 app[web.1]: mod = importlib.import_module(module)
2023-05-23T13:39:29.248725+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:39:29.248725+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
2023-05-23T13:39:29.248726+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2023-05-23T13:39:29.248726+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:39:29.248726+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2023-05-23T13:39:29.248726+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2023-05-23T13:39:29.248726+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
2023-05-23T13:39:29.248726+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2023-05-23T13:39:29.248726+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2023-05-23T13:39:29.248727+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-05-23T13:39:29.248727+00:00 app[web.1]: File "/app/peaknutrition/wsgi.py", line 16, in <module>
2023-05-23T13:39:29.248727+00:00 app[web.1]: application = get_wsgi_application()
2023-05-23T13:39:29.248727+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:39:29.248727+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2023-05-23T13:39:29.248727+00:00 app[web.1]: django.setup(set_prefix=False)
2023-05-23T13:39:29.248727+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
2023-05-23T13:39:29.248728+00:00 app[web.1]: apps.populate(settings.INSTALLED_APPS)
2023-05-23T13:39:29.248728+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/registry.py", line 91, in populate
2023-05-23T13:39:29.248728+00:00 app[web.1]: app_config = AppConfig.create(entry)
2023-05-23T13:39:29.248728+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:39:29.248728+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/config.py", line 224, in create
2023-05-23T13:39:29.248729+00:00 app[web.1]: import_module(entry)
2023-05-23T13:39:29.248729+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
2023-05-23T13:39:29.248729+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2023-05-23T13:39:29.248729+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:39:29.248730+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2023-05-23T13:39:29.248730+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2023-05-23T13:39:29.248730+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
2023-05-23T13:39:29.248730+00:00 app[web.1]: ModuleNotFoundError: No module named 'taggit'
2023-05-23T13:39:29.248807+00:00 app[web.1]: [2023-05-23 13:39:29 +0000] [7] [INFO] Worker exiting (pid: 7)
2023-05-23T13:39:29.248810+00:00 app[web.1]: [2023-05-23 13:39:29 +0000] [8] [INFO] Worker exiting (pid: 8)
2023-05-23T13:39:29.301102+00:00 app[web.1]: Traceback (most recent call last):
2023-05-23T13:39:29.301109+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 209, in run
2023-05-23T13:39:29.301250+00:00 app[web.1]: self.sleep()
2023-05-23T13:39:29.301283+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 357, in sleep
2023-05-23T13:39:29.301364+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2023-05-23T13:39:29.301547+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:39:29.301556+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2023-05-23T13:39:29.301609+00:00 app[web.1]: self.reap_workers()
2023-05-23T13:39:29.301626+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2023-05-23T13:39:29.301711+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2023-05-23T13:39:29.301761+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-05-23T13:39:29.301768+00:00 app[web.1]: 
2023-05-23T13:39:29.301776+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2023-05-23T13:39:29.301777+00:00 app[web.1]: 
2023-05-23T13:39:29.301786+00:00 app[web.1]: Traceback (most recent call last):
2023-05-23T13:39:29.301795+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2023-05-23T13:39:29.301831+00:00 app[web.1]: sys.exit(run())
2023-05-23T13:39:29.301895+00:00 app[web.1]: ^^^^^
2023-05-23T13:39:29.301903+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2023-05-23T13:39:29.301967+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2023-05-23T13:39:29.301994+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/base.py", line 231, in run
2023-05-23T13:39:29.302049+00:00 app[web.1]: super().run()
2023-05-23T13:39:29.302069+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
2023-05-23T13:39:29.302110+00:00 app[web.1]: Arbiter(self).run()
2023-05-23T13:39:29.302126+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 229, in run
2023-05-23T13:39:29.302179+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2023-05-23T13:39:29.302202+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 342, in halt
2023-05-23T13:39:29.302265+00:00 app[web.1]: self.stop()
2023-05-23T13:39:29.302280+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 393, in stop
2023-05-23T13:39:29.302351+00:00 app[web.1]: time.sleep(0.1)
2023-05-23T13:39:29.302369+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2023-05-23T13:39:29.302414+00:00 app[web.1]: self.reap_workers()
2023-05-23T13:39:29.302429+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2023-05-23T13:39:29.302497+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2023-05-23T13:39:29.302538+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-05-23T13:39:29.451441+00:00 heroku[web.1]: Process exited with status 1
2023-05-23T13:39:29.477930+00:00 heroku[web.1]: State changed from up to crashed
2023-05-23T13:39:34.549542+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=peak-nutrition.herokuapp.com request_id=8b4aa172-d6ee-40f9-8a5c-d15a273e51d9 fwd="87.33.96.2" dyno= connect= service= status=503 bytes= protocol=https
2023-05-23T13:39:36.849928+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=peak-nutrition.herokuapp.com request_id=4730e996-46e4-43b5-b193-94bf1afb6ed8 fwd="87.33.96.2" dyno= connect= service= status=503 bytes= protocol=https
2023-05-23T13:40:55.823091+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=peak-nutrition.herokuapp.com request_id=63a5a165-326a-48d6-ad99-25db3bc21d33 fwd="87.33.96.2" dyno= connect= service= status=503 bytes= protocol=https
2023-05-23T13:40:57.484779+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=peak-nutrition.herokuapp.com request_id=f0b0c6b5-616b-4d46-8bca-ffd1d35a1fe6 fwd="87.33.96.2" dyno= connect= service= status=503 bytes= protocol=https
2023-05-23T13:45:13.023068+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=peak-nutrition.herokuapp.com request_id=ae842b25-7a17-4043-82c1-646123c59a00 fwd="87.33.96.2" dyno= connect= service= status=503 bytes= protocol=https
2023-05-23T13:45:14.667604+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=peak-nutrition.herokuapp.com request_id=c99b08b1-db7b-41aa-8570-b58f67b8deb4 fwd="87.33.96.2" dyno= connect= service= status=503 bytes= protocol=https
2023-05-23T13:49:46.911765+00:00 heroku[web.1]: State changed from crashed to starting
2023-05-23T13:49:49.707025+00:00 heroku[web.1]: Starting process with command `gunicorn peaknutrition.wsgi:application`
2023-05-23T13:49:51.279778+00:00 heroku[web.1]: State changed from starting to up
2023-05-23T13:49:51.073715+00:00 app[web.1]: [2023-05-23 13:49:51 +0000] [2] [INFO] Starting gunicorn 20.1.0
2023-05-23T13:49:51.074001+00:00 app[web.1]: [2023-05-23 13:49:51 +0000] [2] [INFO] Listening at: http://0.0.0.0:55528 (2)
2023-05-23T13:49:51.074035+00:00 app[web.1]: [2023-05-23 13:49:51 +0000] [2] [INFO] Using worker: sync
2023-05-23T13:49:51.076194+00:00 app[web.1]: [2023-05-23 13:49:51 +0000] [7] [INFO] Booting worker with pid: 7
2023-05-23T13:49:51.123315+00:00 app[web.1]: [2023-05-23 13:49:51 +0000] [8] [INFO] Booting worker with pid: 8
2023-05-23T13:49:51.561165+00:00 app[web.1]: [2023-05-23 13:49:51 +0000] [8] [ERROR] Exception in worker process
2023-05-23T13:49:51.561177+00:00 app[web.1]: Traceback (most recent call last):
2023-05-23T13:49:51.561178+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-05-23T13:49:51.561179+00:00 app[web.1]: worker.init_process()
2023-05-23T13:49:51.561179+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-05-23T13:49:51.561180+00:00 app[web.1]: self.load_wsgi()
2023-05-23T13:49:51.561181+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-05-23T13:49:51.561181+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2023-05-23T13:49:51.561181+00:00 app[web.1]: ^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561181+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-05-23T13:49:51.561182+00:00 app[web.1]: self.callable = self.load()
2023-05-23T13:49:51.561182+00:00 app[web.1]: ^^^^^^^^^^^
2023-05-23T13:49:51.561182+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-05-23T13:49:51.561182+00:00 app[web.1]: return self.load_wsgiapp()
2023-05-23T13:49:51.561183+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561183+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-05-23T13:49:51.561183+00:00 app[web.1]: return util.import_app(self.app_uri)
2023-05-23T13:49:51.561183+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561183+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
2023-05-23T13:49:51.561184+00:00 app[web.1]: mod = importlib.import_module(module)
2023-05-23T13:49:51.561184+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561185+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
2023-05-23T13:49:51.561185+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2023-05-23T13:49:51.561185+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561185+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2023-05-23T13:49:51.561186+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2023-05-23T13:49:51.561186+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
2023-05-23T13:49:51.561186+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2023-05-23T13:49:51.561186+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2023-05-23T13:49:51.561187+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-05-23T13:49:51.561187+00:00 app[web.1]: File "/app/peaknutrition/wsgi.py", line 16, in <module>
2023-05-23T13:49:51.561187+00:00 app[web.1]: application = get_wsgi_application()
2023-05-23T13:49:51.561187+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561188+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2023-05-23T13:49:51.561188+00:00 app[web.1]: django.setup(set_prefix=False)
2023-05-23T13:49:51.561188+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
2023-05-23T13:49:51.561188+00:00 app[web.1]: apps.populate(settings.INSTALLED_APPS)
2023-05-23T13:49:51.561188+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/registry.py", line 91, in populate
2023-05-23T13:49:51.561189+00:00 app[web.1]: app_config = AppConfig.create(entry)
2023-05-23T13:49:51.561189+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561189+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/config.py", line 224, in create
2023-05-23T13:49:51.561189+00:00 app[web.1]: import_module(entry)
2023-05-23T13:49:51.561190+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
2023-05-23T13:49:51.561190+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2023-05-23T13:49:51.561190+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561190+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2023-05-23T13:49:51.561190+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2023-05-23T13:49:51.561191+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
2023-05-23T13:49:51.561191+00:00 app[web.1]: ModuleNotFoundError: No module named 'taggit'
2023-05-23T13:49:51.561194+00:00 app[web.1]: [2023-05-23 13:49:51 +0000] [7] [ERROR] Exception in worker process
2023-05-23T13:49:51.561195+00:00 app[web.1]: Traceback (most recent call last):
2023-05-23T13:49:51.561214+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-05-23T13:49:51.561214+00:00 app[web.1]: worker.init_process()
2023-05-23T13:49:51.561214+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-05-23T13:49:51.561214+00:00 app[web.1]: self.load_wsgi()
2023-05-23T13:49:51.561214+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-05-23T13:49:51.561215+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2023-05-23T13:49:51.561215+00:00 app[web.1]: ^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561215+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-05-23T13:49:51.561215+00:00 app[web.1]: self.callable = self.load()
2023-05-23T13:49:51.561215+00:00 app[web.1]: ^^^^^^^^^^^
2023-05-23T13:49:51.561216+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-05-23T13:49:51.561216+00:00 app[web.1]: return self.load_wsgiapp()
2023-05-23T13:49:51.561216+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561216+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-05-23T13:49:51.561216+00:00 app[web.1]: return util.import_app(self.app_uri)
2023-05-23T13:49:51.561216+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561216+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
2023-05-23T13:49:51.561217+00:00 app[web.1]: mod = importlib.import_module(module)
2023-05-23T13:49:51.561217+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561217+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
2023-05-23T13:49:51.561217+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2023-05-23T13:49:51.561217+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561217+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2023-05-23T13:49:51.561218+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2023-05-23T13:49:51.561218+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
2023-05-23T13:49:51.561218+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2023-05-23T13:49:51.561218+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2023-05-23T13:49:51.561218+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-05-23T13:49:51.561219+00:00 app[web.1]: File "/app/peaknutrition/wsgi.py", line 16, in <module>
2023-05-23T13:49:51.561220+00:00 app[web.1]: application = get_wsgi_application()
2023-05-23T13:49:51.561220+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561220+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2023-05-23T13:49:51.561220+00:00 app[web.1]: django.setup(set_prefix=False)
2023-05-23T13:49:51.561220+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
2023-05-23T13:49:51.561220+00:00 app[web.1]: apps.populate(settings.INSTALLED_APPS)
2023-05-23T13:49:51.561221+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/registry.py", line 91, in populate
2023-05-23T13:49:51.561221+00:00 app[web.1]: app_config = AppConfig.create(entry)
2023-05-23T13:49:51.561221+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561221+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/config.py", line 224, in create
2023-05-23T13:49:51.561222+00:00 app[web.1]: import_module(entry)
2023-05-23T13:49:51.561222+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
2023-05-23T13:49:51.561222+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2023-05-23T13:49:51.561222+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.561222+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2023-05-23T13:49:51.561223+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2023-05-23T13:49:51.561223+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
2023-05-23T13:49:51.561223+00:00 app[web.1]: ModuleNotFoundError: No module named 'taggit'
2023-05-23T13:49:51.561300+00:00 app[web.1]: [2023-05-23 13:49:51 +0000] [8] [INFO] Worker exiting (pid: 8)
2023-05-23T13:49:51.561325+00:00 app[web.1]: [2023-05-23 13:49:51 +0000] [7] [INFO] Worker exiting (pid: 7)
2023-05-23T13:49:51.617618+00:00 app[web.1]: Traceback (most recent call last):
2023-05-23T13:49:51.617623+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 209, in run
2023-05-23T13:49:51.617816+00:00 app[web.1]: self.sleep()
2023-05-23T13:49:51.617864+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 357, in sleep
2023-05-23T13:49:51.617989+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2023-05-23T13:49:51.618188+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T13:49:51.618196+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2023-05-23T13:49:51.618294+00:00 app[web.1]: self.reap_workers()
2023-05-23T13:49:51.618315+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2023-05-23T13:49:51.618446+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2023-05-23T13:49:51.618502+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-05-23T13:49:51.618503+00:00 app[web.1]: 
2023-05-23T13:49:51.618513+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2023-05-23T13:49:51.618514+00:00 app[web.1]: 
2023-05-23T13:49:51.618524+00:00 app[web.1]: Traceback (most recent call last):
2023-05-23T13:49:51.618533+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2023-05-23T13:49:51.618593+00:00 app[web.1]: sys.exit(run())
2023-05-23T13:49:51.618660+00:00 app[web.1]: ^^^^^
2023-05-23T13:49:51.618670+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2023-05-23T13:49:51.618743+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2023-05-23T13:49:51.618770+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/base.py", line 231, in run
2023-05-23T13:49:51.618854+00:00 app[web.1]: super().run()
2023-05-23T13:49:51.618880+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
2023-05-23T13:49:51.618940+00:00 app[web.1]: Arbiter(self).run()
2023-05-23T13:49:51.618962+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 229, in run
2023-05-23T13:49:51.619041+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2023-05-23T13:49:51.619074+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 342, in halt
2023-05-23T13:49:51.619162+00:00 app[web.1]: self.stop()
2023-05-23T13:49:51.619184+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 382, in stop
2023-05-23T13:49:51.619283+00:00 app[web.1]: sock.close_sockets(self.LISTENERS, unlink)
2023-05-23T13:49:51.619309+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/sock.py", line 210, in close_sockets
2023-05-23T13:49:51.619385+00:00 app[web.1]: sock.close()
2023-05-23T13:49:51.619404+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/sock.py", line 67, in close
2023-05-23T13:49:51.619459+00:00 app[web.1]: self.sock.close()
2023-05-23T13:49:51.619478+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/socket.py", line 503, in close
2023-05-23T13:49:51.619651+00:00 app[web.1]: self._real_close()
2023-05-23T13:49:51.619672+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/socket.py", line 497, in _real_close
2023-05-23T13:49:51.619828+00:00 app[web.1]: _ss.close(self)
2023-05-23T13:49:51.619848+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2023-05-23T13:49:51.619946+00:00 app[web.1]: self.reap_workers()
2023-05-23T13:49:51.619965+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2023-05-23T13:49:51.620083+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2023-05-23T13:49:51.620128+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-05-23T13:49:51.769311+00:00 heroku[web.1]: Process exited with status 1
2023-05-23T13:49:51.794608+00:00 heroku[web.1]: State changed from up to crashed